CREATE TABLE flowers ( 
    id INT AUTO_INCREMENT PRIMARY KEY,
    owner TEXT NOT NULL, 
    wunsch TEXT, 
    time TEXT
);

-- andre.reitter@gilead.com (26 rows)
INSERT INTO flowers (owner, wunsch, time)
VALUES
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', ''),
('andre.reitter@gilead.com', '', '');

-- monika.poelzleitner@gilead.com (26 rows)
INSERT INTO flowers (owner, wunsch, time)
VALUES
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', ''),
('monika.poelzleitner@gilead.com', '', '');

-- jelena.grubesic@gilead.com (27 rows)
INSERT INTO flowers (owner, wunsch, time)
VALUES
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', ''),
('jelena.grubesic@gilead.com', '', '');