CREATE TABLE flowers ( 
    id INT AUTO_INCREMENT PRIMARY KEY,
    owner TEXT NOT NULL, 
    wunsch TEXT, 
    time TEXT
);

-- person1 (26 rows)
INSERT INTO flowers (owner, wunsch, time)
VALUES
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', ''),
('person1', '', '');

-- person2 (26 rows)
INSERT INTO flowers (owner, wunsch, time)
VALUES
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', ''),
('person2', '', '');

-- person3 (27 rows)
INSERT INTO flowers (owner, wunsch, time)
VALUES
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', ''),
('person3', '', '');